name: .NET Core CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --no-restore -c Release
      
    - name: Run xUnit Tests
      run: dotnet test --no-build --verbosity normal -c Release

  publish-nuget:
    needs: build-and-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Pack Core Library
      run: dotnet pack AbstractPayments.Core/AbstractPayments.Core.csproj -c Release -o ./artifacts /p:Version=${{ github.event.release.tag_name }}

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: v1tor2003
      
    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ steps.login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json